// Package realtimeOpenapi3 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
//package realtimeOpenapi3
package voiceai

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/deepmap/oapi-codegen/pkg/runtime"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for RealtimeRealtimeRequestCommandType1.
const (
	ConversationItemCreate   RealtimeRealtimeRequestCommandType1 = "conversation.item.create"
	ConversationItemDelete   RealtimeRealtimeRequestCommandType1 = "conversation.item.delete"
	ConversationItemTruncate RealtimeRealtimeRequestCommandType1 = "conversation.item.truncate"
	InputAudioBufferAppend   RealtimeRealtimeRequestCommandType1 = "input_audio_buffer.append"
	InputAudioBufferClear    RealtimeRealtimeRequestCommandType1 = "input_audio_buffer.clear"
	InputAudioBufferCommit   RealtimeRealtimeRequestCommandType1 = "input_audio_buffer.commit"
	ResponseCancel           RealtimeRealtimeRequestCommandType1 = "response.cancel"
	ResponseCreate           RealtimeRealtimeRequestCommandType1 = "response.create"
	SessionUpdate            RealtimeRealtimeRequestCommandType1 = "session.update"
)

// Defines values for RealtimeRealtimeResponseCommandType1.
const (
	ConversationItemCreated                          RealtimeRealtimeResponseCommandType1 = "conversation.item.created"
	ConversationItemDeleted                          RealtimeRealtimeResponseCommandType1 = "conversation.item.deleted"
	ConversationItemInputAudioTranscriptionCompleted RealtimeRealtimeResponseCommandType1 = "conversation.item.input_audio_transcription.completed"
	ConversationItemInputAudioTranscriptionFailed    RealtimeRealtimeResponseCommandType1 = "conversation.item.input_audio_transcription.failed"
	ConversationItemTruncated                        RealtimeRealtimeResponseCommandType1 = "conversation.item.truncated"
	Error                                            RealtimeRealtimeResponseCommandType1 = "error"
	InputAudioBufferCleared                          RealtimeRealtimeResponseCommandType1 = "input_audio_buffer.cleared"
	InputAudioBufferCommitted                        RealtimeRealtimeResponseCommandType1 = "input_audio_buffer.committed"
	InputAudioBufferSpeechStarted                    RealtimeRealtimeResponseCommandType1 = "input_audio_buffer.speech_started"
	InputAudioBufferSpeechStopped                    RealtimeRealtimeResponseCommandType1 = "input_audio_buffer.speech_stopped"
	RateLimitsUpdated                                RealtimeRealtimeResponseCommandType1 = "rate_limits.updated"
	ResponseAudioDelta                               RealtimeRealtimeResponseCommandType1 = "response.audio.delta"
	ResponseAudioDone                                RealtimeRealtimeResponseCommandType1 = "response.audio.done"
	ResponseAudioTranscriptDelta                     RealtimeRealtimeResponseCommandType1 = "response.audio_transcript.delta"
	ResponseAudioTranscriptDone                      RealtimeRealtimeResponseCommandType1 = "response.audio_transcript.done"
	ResponseContentPartAdded                         RealtimeRealtimeResponseCommandType1 = "response.content_part.added"
	ResponseContentPartDone                          RealtimeRealtimeResponseCommandType1 = "response.content_part.done"
	ResponseCreated                                  RealtimeRealtimeResponseCommandType1 = "response.created"
	ResponseDone                                     RealtimeRealtimeResponseCommandType1 = "response.done"
	ResponseFunctionCallArgumentsDelta               RealtimeRealtimeResponseCommandType1 = "response.function_call_arguments.delta"
	ResponseFunctionCallArgumentsDone                RealtimeRealtimeResponseCommandType1 = "response.function_call_arguments.done"
	ResponseOutputItemAdded                          RealtimeRealtimeResponseCommandType1 = "response.output_item.added"
	ResponseOutputItemDone                           RealtimeRealtimeResponseCommandType1 = "response.output_item.done"
	ResponseTextDelta                                RealtimeRealtimeResponseCommandType1 = "response.text.delta"
	ResponseTextDone                                 RealtimeRealtimeResponseCommandType1 = "response.text.done"
	SessionCreated                                   RealtimeRealtimeResponseCommandType1 = "session.created"
	SessionUpdated                                   RealtimeRealtimeResponseCommandType1 = "session.updated"
)

// RealtimeRealtimeRequestCommand A base representation for messages sent by the client to the service.
type RealtimeRealtimeRequestCommand struct {
	EventId *string                            `json:"event_id,omitempty"`
	Type    RealtimeRealtimeRequestCommandType `json:"type"`
}

// RealtimeRealtimeRequestCommandType defines model for Realtime.RealtimeRequestCommandType.
type RealtimeRealtimeRequestCommandType struct {
	union json.RawMessage
}

// RealtimeRealtimeRequestCommandType0 defines model for .
type RealtimeRealtimeRequestCommandType0 = string

// RealtimeRealtimeRequestCommandType1 defines model for RealtimeRealtimeRequestCommandType.1.
type RealtimeRealtimeRequestCommandType1 string

// RealtimeRealtimeResponseCommand Base representation of a WebSocket message received from the service.
type RealtimeRealtimeResponseCommand struct {
	EventId *string                             `json:"event_id"`
	Type    RealtimeRealtimeResponseCommandType `json:"type"`
}

// RealtimeRealtimeResponseCommandType defines model for Realtime.RealtimeResponseCommandType.
type RealtimeRealtimeResponseCommandType struct {
	union json.RawMessage
}

// RealtimeRealtimeResponseCommandType0 defines model for .
type RealtimeRealtimeResponseCommandType0 = string

// RealtimeRealtimeResponseCommandType1 defines model for RealtimeRealtimeResponseCommandType.1.
type RealtimeRealtimeResponseCommandType1 string

// RealtimeStartRealtimeSessionJSONBody defines parameters for RealtimeStartRealtimeSession.
type RealtimeStartRealtimeSessionJSONBody = []RealtimeRealtimeRequestCommand

// RealtimeStartRealtimeSessionJSONRequestBody defines body for RealtimeStartRealtimeSession for application/json ContentType.
type RealtimeStartRealtimeSessionJSONRequestBody = RealtimeStartRealtimeSessionJSONBody

// AsRealtimeRealtimeRequestCommandType0 returns the union data inside the RealtimeRealtimeRequestCommandType as a RealtimeRealtimeRequestCommandType0
func (t RealtimeRealtimeRequestCommandType) AsRealtimeRealtimeRequestCommandType0() (RealtimeRealtimeRequestCommandType0, error) {
	var body RealtimeRealtimeRequestCommandType0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRealtimeRealtimeRequestCommandType0 overwrites any union data inside the RealtimeRealtimeRequestCommandType as the provided RealtimeRealtimeRequestCommandType0
func (t *RealtimeRealtimeRequestCommandType) FromRealtimeRealtimeRequestCommandType0(v RealtimeRealtimeRequestCommandType0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRealtimeRealtimeRequestCommandType0 performs a merge with any union data inside the RealtimeRealtimeRequestCommandType, using the provided RealtimeRealtimeRequestCommandType0
func (t *RealtimeRealtimeRequestCommandType) MergeRealtimeRealtimeRequestCommandType0(v RealtimeRealtimeRequestCommandType0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	//merged, err := JsonMerge(t.union, b)
	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

// AsRealtimeRealtimeRequestCommandType1 returns the union data inside the RealtimeRealtimeRequestCommandType as a RealtimeRealtimeRequestCommandType1
func (t RealtimeRealtimeRequestCommandType) AsRealtimeRealtimeRequestCommandType1() (RealtimeRealtimeRequestCommandType1, error) {
	var body RealtimeRealtimeRequestCommandType1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRealtimeRealtimeRequestCommandType1 overwrites any union data inside the RealtimeRealtimeRequestCommandType as the provided RealtimeRealtimeRequestCommandType1
func (t *RealtimeRealtimeRequestCommandType) FromRealtimeRealtimeRequestCommandType1(v RealtimeRealtimeRequestCommandType1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRealtimeRealtimeRequestCommandType1 performs a merge with any union data inside the RealtimeRealtimeRequestCommandType, using the provided RealtimeRealtimeRequestCommandType1
func (t *RealtimeRealtimeRequestCommandType) MergeRealtimeRealtimeRequestCommandType1(v RealtimeRealtimeRequestCommandType1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

func (t RealtimeRealtimeRequestCommandType) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *RealtimeRealtimeRequestCommandType) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsRealtimeRealtimeResponseCommandType0 returns the union data inside the RealtimeRealtimeResponseCommandType as a RealtimeRealtimeResponseCommandType0
func (t RealtimeRealtimeResponseCommandType) AsRealtimeRealtimeResponseCommandType0() (RealtimeRealtimeResponseCommandType0, error) {
	var body RealtimeRealtimeResponseCommandType0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRealtimeRealtimeResponseCommandType0 overwrites any union data inside the RealtimeRealtimeResponseCommandType as the provided RealtimeRealtimeResponseCommandType0
func (t *RealtimeRealtimeResponseCommandType) FromRealtimeRealtimeResponseCommandType0(v RealtimeRealtimeResponseCommandType0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRealtimeRealtimeResponseCommandType0 performs a merge with any union data inside the RealtimeRealtimeResponseCommandType, using the provided RealtimeRealtimeResponseCommandType0
func (t *RealtimeRealtimeResponseCommandType) MergeRealtimeRealtimeResponseCommandType0(v RealtimeRealtimeResponseCommandType0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

// AsRealtimeRealtimeResponseCommandType1 returns the union data inside the RealtimeRealtimeResponseCommandType as a RealtimeRealtimeResponseCommandType1
func (t RealtimeRealtimeResponseCommandType) AsRealtimeRealtimeResponseCommandType1() (RealtimeRealtimeResponseCommandType1, error) {
	var body RealtimeRealtimeResponseCommandType1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRealtimeRealtimeResponseCommandType1 overwrites any union data inside the RealtimeRealtimeResponseCommandType as the provided RealtimeRealtimeResponseCommandType1
func (t *RealtimeRealtimeResponseCommandType) FromRealtimeRealtimeResponseCommandType1(v RealtimeRealtimeResponseCommandType1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRealtimeRealtimeResponseCommandType1 performs a merge with any union data inside the RealtimeRealtimeResponseCommandType, using the provided RealtimeRealtimeResponseCommandType1
func (t *RealtimeRealtimeResponseCommandType) MergeRealtimeRealtimeResponseCommandType1(v RealtimeRealtimeResponseCommandType1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

func (t RealtimeRealtimeResponseCommandType) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *RealtimeRealtimeResponseCommandType) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// RealtimeStartRealtimeSessionWithBody request with any body
	RealtimeStartRealtimeSessionWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	RealtimeStartRealtimeSession(ctx context.Context, body RealtimeStartRealtimeSessionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) RealtimeStartRealtimeSessionWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRealtimeStartRealtimeSessionRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RealtimeStartRealtimeSession(ctx context.Context, body RealtimeStartRealtimeSessionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRealtimeStartRealtimeSessionRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewRealtimeStartRealtimeSessionRequest calls the generic RealtimeStartRealtimeSession builder with application/json body
func NewRealtimeStartRealtimeSessionRequest(server string, body RealtimeStartRealtimeSessionJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRealtimeStartRealtimeSessionRequestWithBody(server, "application/json", bodyReader)
}

// NewRealtimeStartRealtimeSessionRequestWithBody generates requests for RealtimeStartRealtimeSession with any type of body
func NewRealtimeStartRealtimeSessionRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/realtime")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// RealtimeStartRealtimeSessionWithBodyWithResponse request with any body
	RealtimeStartRealtimeSessionWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RealtimeStartRealtimeSessionResponse, error)

	RealtimeStartRealtimeSessionWithResponse(ctx context.Context, body RealtimeStartRealtimeSessionJSONRequestBody, reqEditors ...RequestEditorFn) (*RealtimeStartRealtimeSessionResponse, error)
}

type RealtimeStartRealtimeSessionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]RealtimeRealtimeResponseCommand
}

// Status returns HTTPResponse.Status
func (r RealtimeStartRealtimeSessionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RealtimeStartRealtimeSessionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// RealtimeStartRealtimeSessionWithBodyWithResponse request with arbitrary body returning *RealtimeStartRealtimeSessionResponse
func (c *ClientWithResponses) RealtimeStartRealtimeSessionWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RealtimeStartRealtimeSessionResponse, error) {
	rsp, err := c.RealtimeStartRealtimeSessionWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRealtimeStartRealtimeSessionResponse(rsp)
}

func (c *ClientWithResponses) RealtimeStartRealtimeSessionWithResponse(ctx context.Context, body RealtimeStartRealtimeSessionJSONRequestBody, reqEditors ...RequestEditorFn) (*RealtimeStartRealtimeSessionResponse, error) {
	rsp, err := c.RealtimeStartRealtimeSession(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRealtimeStartRealtimeSessionResponse(rsp)
}

// ParseRealtimeStartRealtimeSessionResponse parses an HTTP response from a RealtimeStartRealtimeSessionWithResponse call
func ParseRealtimeStartRealtimeSessionResponse(rsp *http.Response) (*RealtimeStartRealtimeSessionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RealtimeStartRealtimeSessionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []RealtimeRealtimeResponseCommand
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Starts a real-time conversation session.
	// (POST /realtime)
	RealtimeStartRealtimeSession(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// RealtimeStartRealtimeSession converts echo context to params.
func (w *ServerInterfaceWrapper) RealtimeStartRealtimeSession(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RealtimeStartRealtimeSession(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/realtime", wrapper.RealtimeStartRealtimeSession)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xYUW/iOBD+K5bvHrOhunvLG2W7UqXTtSqc7qFCyDiT4r3E9tpOtQjx30/jJCSUJICL",
	"9qlJir9vxp75ZsY7ylWhlQTpLE121PINFMw/vgDLnSggbh5e4EcJ1s1UUTCZ4k9SsNwI7YSSNKFTsmYW",
	"iAFtwIJ0DL+TTBlSgLXsDSzBz2S9JW4DhOcC35zybxbMu+AQ04imAlELIZlTBmkKprWQb/jIlXwHYz10",
	"LBwUMTfAHNCE/jZpXZnUfkyGnHh0UMz8ysadqAc7hRzCsL/6lWPYzpSSB1q+qNe2+ELq0q1YmQq1WpdZ",
	"BiZmWgMe05XwCDRFnHsPM/Uoo0Q8B2Y+yzNDkHEaVRTCfZrHo7REBqxW0kLMmeSQXwv/Ui+f+dV9sEHh",
	"eYD9EKIWrMUIKnUagDqvVv/jFzeg+4hqozQYt/2bFYjptho6nwV4OYB3kG4lfN77XyTUOoNpuY/qDzv6",
	"u4HsWqtqQxaedY9b96MUBlKavFa4ywafqvV34A4JLwFLdpTJ7VNGk9dTk3cUZFkgx4c9HculsbgcSY1o",
	"WLZGVGdUNE4j7DSU231rvF7271wda0O6ft+j6iojjPwL67ni/4FrBJ4Y4CDeISWZUcUtdP0a/arcaJU9",
	"PS/tYfCVuI/Cd2PBGSYP+4nhosOpWzlbdFFnDWiYTRkT+W0N+uYRL6l/YbRNBexQgDHKXA32gKvOl7cQ",
	"M/sqHKQX1Dh3C7YGaZTPagC+WVnHzC1I5x5uXqFdRqy0viGxR+tUYeZglYtCOFvL+/VUL8zBXx6iqptp",
	"T5H3rqGkOHY1vvfiKy4dBlYSAnGVhCHYjgZ8xvQ27UedOGIL9qdD1u8ZV9Jhn6KZcTFL04ADn1UQz8y4",
	"KQKcYwnypkMy5Elg/TupfQfEIEMHrMtKyVHLV5zl+YqZt7JAvMBA+lajzVieTxusoXAapA5xr5+532dV",
	"OtQxX73CQuvJI2D9GoqsLkeQQy3FgBcOfobm+wJ+DiZ5BRtisUc9srXpyENToJ5zTjLhuNMPxv1QB0IG",
	"KFnmOVvnQBNnSohuNlAddfLDE1XUGnPhcHUKfOV01Zzl6SlEI83/WOc+3lT2KOlHKezvD0YTfixTx6vQ",
	"aPUYaCX6G4Hzdfxs7e2Xg95svljzL1XoS/rQS1rG0KkraDI606yPzg3NZNI3ju8xHXhphNvOMasrpbjH",
	"hWZaus3hShaXrf1neoDZOKfpHjGEzNTp3L7YAHnSIKeP5OVhviDT58eYPOeA47wFILjeJpOJzpnLlCli",
	"pUEygX5NUsXthGnxxUAGBiSH6iJXGSApOCZyiyO9Ew5FjNY00+dHGlHc3MqCu/guvkNF8cha0IT+6T9F",
	"VDO38c5OTC0y+KKVdfgXddOfzyOqdCNDfrA4vFQyQit5A+vuVbqtrxIwvbxAaZ0L7oEm3y2a1Nxw4xMe",
	"vf3krVWr1ZQZw7bVebSCi/K+b1PD0/1xd/dL7Dy+1uk19DRg6s0kG2aJLTkHSCGNfRmxZVEws6UJ9Qdh",
	"CSN4dl+QjXSTijQSjxHC3izWgcYsutx3o95Xj268vy73S/y3QTT/32Mb60h7kKlWQjoa0dLkdTJgMDMt",
	"OnFMEaw2YUdlVZ4PpuyX+/8DAAD///XsyQsAGQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
