; extensions.conf - the Asterisk dial plan
[general]
static=yes
writeprotect=no
clearglobalvars=no
[globals]
CONSOLE=Console/dsp				; Console interface for demo
IAXINFO=guest					; IAXtel username/password
TRUNK=DAHDI/G2					; Trunk interface
TRUNKMSD=1					; MSD digits to strip (usually 1 or 0)

; Asterisk Voice AI Service Dialplan
[voice-ai-service]
exten => _X.,1,noOp()
    same => n,Answer()
    same => n,Playback(silence/1)
    same => n,Stasis(voicebot)
    same => n,Hangup()

exten => e,1,noOp()
    same => n,Playback(you-dialed-wrong-number)
    same => n,Hangup()

[vais-transfer-out]
exten => s,1,noOp()
	same => n,Transfer(PJSIP/${VAIS_TRANSFER_URI})

[vais-dial-out]
exten => s,1,noOp()
	same => n,Dial(PJSIP/vais-trunk/${VAIS_DIAL_URI})

[vais-dial-local]
exten => s,1,noOp()
	same => n,Dial(local/${VAIS_DIAL_URI},,WXh)

[vais-ivr-demo]
exten => 6120,1,NoOp
	same => n,Playback(ttscache_saminsupport)
	same => n,Hangup()

exten => 6121,1,NoOp
	same => n,Playback(ttscache_tominsales)
	same => n,Hangup()

exten => 6122,1,NoOp
	same => n,Playback(ttscache_mattinaccounts)
	same => n,Hangup()

exten => 6123,1,NoOp
	same => n,Playback(ttscache_pleasehaveaniceday)
	same => n,Hangup()