[system]
type=system
timer_t1=100
timer_b=6400

[global]
type=global
endpoint_identifier_order=username,ip

[transport-udp]
type=transport
protocol=udp    ;udp,tcp,tls,ws,wss,flow
bind=0.0.0.0:5060

[endpoint-template](!)
type=endpoint
context=default
allow=!all,ulaw,alaw
media_address=127.0.0.1
identify_by=ip
100rel=peer_supported


[unknown](endpoint-template)
context=does-not-exist

[identify-template](!)
type=identify

[endpoint-basic](!)
type=endpoint
context=voice-ai-service
transport=transport-udp
disallow=all
allow=all

[auth-userpass](!)
type=auth
auth_type=userpass

[aor-single-reg](!)
type=aor
max_contacts=1

[1000](endpoint-basic)
auth=1000
aors=1000

[1000](auth-userpass)
password=onethousand
username=1000

[1000](aor-single-reg)

[1001](endpoint-basic)
auth=1001
aors=1001

[1001](auth-userpass)
password=onethousandone
username=1001

[1001](aor-single-reg)

[1002](endpoint-basic)
auth=1002
aors=1002

[1002](auth-userpass)
password=onethousandtwo
username=1002

[1002](aor-single-reg)

